name: v2 Test

on:
  workflow_dispatch

env:
  NODE_VERSION: '16.x'

jobs:  
  app:
    name: App Build

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: |
          cd website/docusaurus-search-local
          yarn install
          yarn build
          cd ../
          yarn install
          mkdir downloads

      - name: Linux/Mac App Build & Copy to downloads
        if: matrix.os != 'windows-latest'
        run: |
          cd website
          GH_TOKEN=${{secrets.GITHUB_TOKEN}} yarn run app-build
          mv dist/*.zip dist/*.dmg dist/*.deb dist/*.AppImage downloads || true

      - name: Windows App Build & Copy to downloads
        if: matrix.os == 'windows-latest'
        run: |
          cd website
          yarn run app-build
          mv dist/*.exe downloads
          mv dist/*.zip downloads

        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.os}}
          path: website/downloads
          
  pdf:
    name: PDF

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: PDF Docker Build
        run: |
          docker compose run pdf
          mkdir downloads
          mv parse/output/*.pdf downloads

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'PDF'
          path: downloads
  web:
    name: Web Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: yarn install, build, and test
      run: |
        cd website/docusaurus-search-local
        yarn install
        yarn build
        cd ../
        yarn install
        yarn run download
        yarn run build
    - name: Deploy
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
      with:
        flags: '-avzr --delete'
        options: ''
        ssh_options: ''
        src: 'website/build/'
        dest: 'root@176.58.122.97:/var/www/sites/avodocs/'
